language: shell
sudo: false
env:
  - EMACS=emacs24
addons:
  apt:
    sources:
      - cassou-emacs
    package:
      - emacs24
      - zsh
script: make --debug=b test emacs=$EMACS
notifications:
  email: 8slashes+travis-ci@gmail.com
