#!/bin/sh
# Programs run in background when starting x.
# These programs are basically for Openbox Window Manager.
# Japanese IM settings are not included in this list.

_feh(){
    test -f "$HOME/.fehbg" &&
    type feh >/dev/null 2>&1 &&
    sh "$HOME/.fehbg"
}

_tint2(){
#tint2 -c ~/.dotfiles/tint2rc &
    tint2 &
}

_dropbox(){
    dropboxd & # done by ~/.config/autostart/dropbox.desktop
}

_volumeicon(){
    volumeicon &
}

_conky(){
    conky -c ~/.dotfiles/conkyrc   >~/.backup/log/conky.log 2>&1 &
    conky -c ~/.dotfiles/conkyrc.2 >~/.backup/log/conky.2.log 2>&1 &
}

_wicd(){
# done by /etc/xdg/autostart/wicd-client.desktop
    wicd-client --tray &
}

_udisksvm(){
# Detection of insertion of an optical disk
    if ! pgrep -lf "udisks-daemon: polling /dev/sr0"; then
        udisks --poll-for-media /dev/sr0
    fi
    udisksvm >/dev/null &
}

_xcompmgr(){
    xcompmgr -c &
}

_saku(){
    (cd ~/src/saku-3.11.1/ && python2 saku.py) &
}

_gkeyring(){
    LANG=C gnome-keyring-daemon --start -c pkcs11 &
}

_nmapplet(){
    nm-applet &
}

for p in $@
do
    _$p
done

