#!/bin/sh
# Programs run in background when starting x.
# These programs are basically for Openbox Window Manager.
# Japanese IM settings are not included in this list.

test -f "$HOME/.fehbg" &&
type feh >/dev/null 2>&1 &&
sh "$HOME/.fehbg"

tint2 &

#dropboxd & # done by ~/.config/autostart/dropbox.desktop

volumeicon &

conky -c ~/.dotfiles/conkyrc   >~/.backup/log/conky.log 2>&1 &
conky -c ~/.dotfiles/conkyrc.2 >~/.backup/log/conky.2.log 2>&1 &

#wicd-client --tray & # done by /etc/xdg/autostart/wicd-client.desktop

# Detection of insertion of an optical disk
if ! pgrep -lf "udisks-daemon: polling /dev/sr0"; then
    udisks --poll-for-media /dev/sr0
fi
udisksvm >/dev/null &

xcompmgr -c &
