---
# https://wiki.archlinux.org/index.php/File_manager_functionality
- hosts: all
  vars:
    packages: [gvfs, gvfs-afc, ntfs-3g]
  sudo: yes
  tasks:
  - name: install packages
    pacman: name={{item}} state=installed
    with_items: packages
    when: ansible_os_family == "Archlinux"
  - name: add user yuk to storage group
    user: append=yes groups=storage name=yuk
