---
# do not forget to add lxpolkit to autostart!
- hosts: all
  vars:
    packages: [udevil]
  sudo: yes
  tasks:
  - name: install packages
    pacman: name={{item}} state=installed
    with_items: packages
    when: ansible_os_family == "Archlinux"
  - name: add user yuk to storage group
    user: append=yes groups=storage name=yuk
